# Generated by Django 2.2 on 2020-03-17 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizrooms', to='users.Profile', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='quizroom',
            name='quiz_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.QuizResponse'),
        ),
        migrations.AddField(
            model_name='quizroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Quiz', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.Question', verbose_name='Текст вопроса'),
        ),
    ]
