# Generated by Django 2.2 on 2020-03-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200317_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizrooms', to='users.Profile', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='quizroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Пользователь'),
        ),
    ]
