# Generated by Django 3.0.2 on 2020-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200311_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
