# Generated by Django 3.0.2 on 2020-03-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Quiz', verbose_name='Тест'),
        ),
    ]
