# Generated by Django 3.0.2 on 2020-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Студент'), ('TE', 'Учитель')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
