# Generated by Django 3.0.2 on 2020-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200307_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Студент'), ('TE', 'Учитель')], max_length=2),
        ),
    ]
